### ISSUE TITLE
Add support for self-signed certificates and puppetdb v4 + report_time over catalog_time

### ISSUE THREAD

**Issue by kasperbrandenburg** [evgeni/check_puppetdb_nodes#4]
Can you make this work for Nagios and puppet v4? i've changed to script to fit my needs, would rather see it properly maintaned here.

To get around the https communication on a self-signed puppetdb certificate, i added
$ua->ssl_opts( verify_hostname => 0 ,SSL_verify_mode => 0x00);

I've change the timestamp used to identify the health of an agent from catalog_timestamp to report_timestamp. This gives me an indication if the agent dropped off the line or not.
(Basically search-replace catalog_timestamp > report_timestamp)

Finally i've changeed the endpoints to match the v4 API rather that v3
my $uri = URI->new( $url . '/api/pdb/query/v4/nodes' );
my $uri = URI->new( $url . 'v4/event-counts' );

See file here: https://gist.github.com/kasperbrandenburg/f538ecd0367ce44bf499

**Comment by evgeni** [comment]
Hi @kasperbrandenburg,

thanks for your suggestions. I have a few comments/questions :)

* no SSL verification: makes sense, I'd add is an an option (like cURL's -k) though
* can you elaborate on the timestamp switch? why is the report one better?
* is the v3 endpoint still working? I'd love not to break compat with older installs just yet.

**Comment by evgeni** [comment]
no certificates implemented: https://github.com/evgeni/check_puppetdb_nodes/commit/149493f1a2fa55669acb9cfc907e32dfb8da1221

**Comment by kasperbrandenburg** [comment]
Hi,

I'm totalyl new to puppet, so maybe im getting this completely wrong. My main objects was to test if a puppet agent stopped reporting into the puppetserver. every time the agent runs, the report_timetamp is updated, making it an ideal candidate for testing if agents are alive.

The catalog_timestamp is only updated if the agent actually applies a change, so its valid if you only want to test on that. I just feel the report_timestamp is better.

v3 api did not work on my v4 box, so to support both, i think you must have a switch to select which version, and check for that in the scriptcode.

if (v4) { ... }
if (v3) { ... }

**Comment by evgeni** [comment]
Hey,

catalog_timestamp is updated when a catalog is applied, this does not imply there were actually changes. That said, I see no reason there should be a huge difference between the two timestamps in reality.

I can't find any fresh puppetdb debs from @puppetlabs, so cannot test the v4 thing right now :(

Greets
